name: Download and Run Private Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and unzip
        run: |
          mkdir server
          curl -L -o file.zip https://itchio-mirror.cb031a832f44726753d6267436f3b414.r2.cloudflarestorage.com/build/944282/3652116-archive-default?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=3edfcce40115d057d0b5606758e7e9ee%2F20240325%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240325T223408Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&X-Amz-Signature=3971e165fee2d8780c7a47e0bff4417f3428daea539dbbb01c317f6013000a61
          tar -xf file.zip -C server

      - name: Run script
        run: |
          cd server
          start run_private.bat
